//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.07 at 10:57:42 AM EST 
//


package org.cisecurity.sacm.xmpp.extensions.repo.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="content" type="{http://cisecurity.org/sacm/repository}SACMRepositoryContentType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "sacm_repository")
public class SacmRepository {

    public static final String NAMESPACE = "http://cisecurity.org/sacm/repository";

    @XmlElement(required = true)
    protected SACMRepositoryContentType content;

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link SACMRepositoryContentType }
     *     
     */
    public SACMRepositoryContentType getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link SACMRepositoryContentType }
     *     
     */
    public void setContent(SACMRepositoryContentType value) {
        this.content = value;
    }

}
