//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.14 at 09:59:14 AM EDT 
//


package org.cisecurity.sacm.xmpp.extensions.repo.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * TBD
 * 
 * <p>Java class for SacmRepositoryContentRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SacmRepositoryContentRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="assessment_content_id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="to_jid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="success" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SacmRepositoryContentRequestType")
public class SacmRepositoryContentRequestType {

    @XmlAttribute(name = "assessment_content_id", required = true)
    protected String assessmentContentId;
    @XmlAttribute(name = "to_jid")
    protected String toJid;
    @XmlAttribute(name = "success")
    protected Boolean success;

    /**
     * Gets the value of the assessmentContentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssessmentContentId() {
        return assessmentContentId;
    }

    /**
     * Sets the value of the assessmentContentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssessmentContentId(String value) {
        this.assessmentContentId = value;
    }

    /**
     * Gets the value of the toJid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToJid() {
        return toJid;
    }

    /**
     * Sets the value of the toJid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToJid(String value) {
        this.toJid = value;
    }

    /**
     * Gets the value of the success property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSuccess() {
        return success;
    }

    /**
     * Sets the value of the success property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSuccess(Boolean value) {
        this.success = value;
    }

}
