//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.14 at 09:59:14 AM EDT 
//


package org.cisecurity.sacm.xmpp.extensions.repo.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * TBD
 * 
 * <p>Java class for SacmRepositoryContentTypeValueType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SacmRepositoryContentTypeValueType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="contentType" use="required" type="{http://cisecurity.org/sacm/repository}SacmRepositoryContentTypeCodeType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SacmRepositoryContentTypeValueType")
public class SacmRepositoryContentTypeValueType {

    @XmlAttribute(name = "contentType", required = true)
    protected SacmRepositoryContentTypeCodeType contentType;

    /**
     * Gets the value of the contentType property.
     * 
     * @return
     *     possible object is
     *     {@link SacmRepositoryContentTypeCodeType }
     *     
     */
    public SacmRepositoryContentTypeCodeType getContentType() {
        return contentType;
    }

    /**
     * Sets the value of the contentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SacmRepositoryContentTypeCodeType }
     *     
     */
    public void setContentType(SacmRepositoryContentTypeCodeType value) {
        this.contentType = value;
    }

}
