//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.07 at 10:57:42 AM EST 
//


package org.cisecurity.sacm.xmpp.extensions.repo.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SACMRepositoryItemTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SACMRepositoryItemTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SCAP"/>
 *     &lt;enumeration value="OVAL"/>
 *     &lt;enumeration value="SACM"/>
 *     &lt;enumeration value="YANG"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SACMRepositoryItemTypeType")
@XmlEnum
public enum SACMRepositoryItemTypeType {


    /**
     * SCAP data-streams, such as XCCDF+OVAL+CPE-Dictionary+CPE-OVAL or a data stream collection
     * 
     */
    SCAP,

    /**
     * OVAL Definitions and Variables
     * 
     */
    OVAL,

    /**
     * SACM Collection data model?
     * 
     */
    SACM,

    /**
     * YANG collection content?
     * 
     */
    YANG;

    public String value() {
        return name();
    }

    public static SACMRepositoryItemTypeType fromValue(String v) {
        return valueOf(v);
    }

}
