//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.24 at 06:17:58 AM EDT 
//


package org.cisecurity.sacm.xmpp.extensions.policy.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://cisecurity.org/sacm/assessment}publisher"/>
 *         &lt;element ref="{http://cisecurity.org/sacm/assessment}policy"/>
 *         &lt;choice>
 *           &lt;element ref="{http://cisecurity.org/sacm/assessment}expected"/>
 *           &lt;element ref="{http://cisecurity.org/sacm/assessment}actual"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "publisher",
    "policy",
    "expected",
    "actual"
})
@XmlRootElement(name = "policy_collection")
public class PolicyCollection {

    public static final String NAMESPACE = "http://cisecurity.org/sacm/policy";

    @XmlElement(required = true)
    protected Publisher publisher;
    @XmlElement(required = true)
    protected Policy policy;
    protected Expected expected;
    protected Actual actual;

    /**
     * Gets the value of the publisher property.
     * 
     * @return
     *     possible object is
     *     {@link Publisher }
     *     
     */
    public Publisher getPublisher() {
        return publisher;
    }

    /**
     * Sets the value of the publisher property.
     * 
     * @param value
     *     allowed object is
     *     {@link Publisher }
     *     
     */
    public void setPublisher(Publisher value) {
        this.publisher = value;
    }

    /**
     * Gets the value of the policy property.
     * 
     * @return
     *     possible object is
     *     {@link Policy }
     *     
     */
    public Policy getPolicy() {
        return policy;
    }

    /**
     * Sets the value of the policy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Policy }
     *     
     */
    public void setPolicy(Policy value) {
        this.policy = value;
    }

    /**
     * Gets the value of the expected property.
     * 
     * @return
     *     possible object is
     *     {@link Expected }
     *     
     */
    public Expected getExpected() {
        return expected;
    }

    /**
     * Sets the value of the expected property.
     * 
     * @param value
     *     allowed object is
     *     {@link Expected }
     *     
     */
    public void setExpected(Expected value) {
        this.expected = value;
    }

    /**
     * Gets the value of the actual property.
     * 
     * @return
     *     possible object is
     *     {@link Actual }
     *     
     */
    public Actual getActual() {
        return actual;
    }

    /**
     * Sets the value of the actual property.
     * 
     * @param value
     *     allowed object is
     *     {@link Actual }
     *     
     */
    public void setActual(Actual value) {
        this.actual = value;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();

        sb.append("Publisher: ").append(publisher.toString()).append("; ");
        sb.append("Policy: ").append(policy.toString()).append("; ");
        if (expected != null) {
            sb.append("Expected: ").append(expected.toString()).append("; ");
        }
        if (actual != null) {
            sb.append("Actual: ").append(actual.toString()).append("; ");
        }
        return sb.toString();
    }
}
