//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.19 at 05:48:29 PM EDT 
//


package org.cisecurity.sacm.xmpp.extensions.assessment.model;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://cisecurity.org/sacm/assessment}datastream_collection"/>
 *         &lt;element ref="{http://cisecurity.org/sacm/assessment}xccdf"/>
 *         &lt;element ref="{http://cisecurity.org/sacm/assessment}oval_definitions"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datastreamCollection",
    "xccdf",
    "ovalDefinitions"
})
@XmlRootElement(name = "assessment")
public class Assessment {

    public static final String NAMESPACE = "http://cisecurity.org/sacm/assessment";

    @XmlElement(name = "datastream_collection")
    protected DatastreamCollection datastreamCollection;
    @XmlElement(name = "xccdf")
    protected Xccdf xccdf;
    @XmlElement(name = "oval_definitions")
    protected OvalDefinitions ovalDefinitions;

    @XmlAttribute(name = "scheduled")
    protected boolean scheduled = false;

    public void setScheduled(boolean scheduled) {
        this.scheduled = scheduled;
    }

    public boolean isScheduled() {
        return scheduled;
    }

    /**
     * Gets the value of the datastreamCollection property.
     * 
     * @return
     *     possible object is
     *     {@link DatastreamCollection }
     *     
     */
    public DatastreamCollection getDatastreamCollection() {
        return datastreamCollection;
    }

    /**
     * Sets the value of the datastreamCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatastreamCollection }
     *     
     */
    public void setDatastreamCollection(DatastreamCollection value) {
        this.datastreamCollection = value;
    }

    /**
     * Gets the value of the xccdf property.
     * 
     * @return
     *     possible object is
     *     {@link Xccdf }
     *     
     */
    public Xccdf getXccdf() {
        return xccdf;
    }

    /**
     * Sets the value of the xccdf property.
     * 
     * @param value
     *     allowed object is
     *     {@link Xccdf }
     *     
     */
    public void setXccdf(Xccdf value) {
        this.xccdf = value;
    }

    /**
     * Gets the value of the ovalDefinitions property.
     * 
     * @return
     *     possible object is
     *     {@link OvalDefinitions }
     *     
     */
    public OvalDefinitions getOvalDefinitions() {
        return ovalDefinitions;
    }

    /**
     * Sets the value of the ovalDefinitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link OvalDefinitions }
     *     
     */
    public void setOvalDefinitions(OvalDefinitions value) {
        this.ovalDefinitions = value;
    }

}
